/* Calistenia Trainer · Fase 9H · Progreso 2.0 */
(function(){'use strict';const V='1.0';
function hist(){try{return typeof loadH==='function'?loadH():JSON.parse(localStorage.getItem('ct_history')||'[]')}catch{return []}}
function checkins(){try{return window.CalisteniaCheckin?.load?.()||JSON.parse(localStorage.getItem('ct_checkins_v1')||'[]')}catch{return []}}
function safety(){try{return window.CalisteniaSafety2?.load?.()||JSON.parse(localStorage.getItem('ct_safety_events_v1')||'[]')}catch{return []}}
function days(n){return Date.now()-n*86400000}function recent(h,n){return h.filter(x=>new Date(x.date||x.day||0).getTime()>=days(n))}
function sessions(h){return h.length}function logs(h){return h.flatMap(x=>x.logs||[])}
function cleanRate(h){const l=logs(h).filter(x=>x.rpe||x.technique);if(!l.length)return null;const ok=l.filter(x=>(x.rpe==='Bien'||x.rpe==='Fácil'||x.rpe==='Facil')&&(x.technique!=='Mala')&&(!x.pain||x.pain==='No')).length;return Math.round(ok/l.length*100)}
function trend(h){const a=recent(h,14),b=h.filter(x=>{const t=new Date(x.date||0).getTime();return t>=days(28)&&t<days(14)});if(a.length>=b.length+2)return ['↑','Progresando','Has entrenado con más regularidad que en las dos semanas anteriores.'];if(a.length&&b.length&&a.length<b.length)return ['→','Consolidar','Tu frecuencia reciente ha bajado. Prioriza volver a la rutina antes de subir dificultad.'];if(a.length)return ['→','Construyendo base','Sigue acumulando sesiones limpias; aún necesitamos más datos para una tendencia fuerte.'];return ['·','Empezando','Completa tus primeras sesiones para que el panel pueda interpretar tu evolución.']}
function progression(name){try{const lvl=levelFor(name),arr=progressions[name],v=arr[lvl];return {lvl,total:arr.length,name:v.name,target:v.target,unit:v.unit,pct:Math.round((lvl+1)/arr.length*100)}}catch{return null}}
function weekCount(h,offset){const now=new Date(),day=(now.getDay()+6)%7,start=new Date(now);start.setHours(0,0,0,0);start.setDate(start.getDate()-day-offset*7);const end=new Date(start);end.setDate(end.getDate()+7);return h.filter(x=>{const d=new Date(x.date);return d>=start&&d<end}).length}
function checkinInsight(){const c=checkins().slice(0,12);if(c.length<2)return 'Aún faltan check-ins para relacionar recuperación y rendimiento.';const red=c.filter(x=>x.plan?.mode==='reduce').length,hold=c.filter(x=>x.plan?.mode==='hold').length;if(red>=3)return 'Has llegado varias veces con recuperación baja. Mantener la carga adaptativa es más importante que acelerar progresiones.';if(red+hold>=Math.ceil(c.length/2))return 'La recuperación ha condicionado varias sesiones recientes; el Coach está haciendo bien en priorizar consolidación.';return 'La mayoría de tus check-ins recientes permiten realizar la carga prevista.'}
function safetyInsight(){const s=recent(safety(),30);if(!s.length)return 'Sin sustituciones o eventos de dolor registrados en los últimos 30 días.';const pain=s.filter(x=>x.reason==='Dolor'||x.severity).length;return `${s.length} ajuste${s.length===1?'':'s'} de seguridad en 30 días${pain?' · '+pain+' relacionado'+(pain===1?'':'s')+' con dolor':''}. Se usan para evitar interpretar una sustitución como fracaso.`}
function bar(p){return `<div style="height:8px;border-radius:8px;background:var(--line);overflow:hidden"><div style="height:100%;width:${Math.max(2,p)}%;background:var(--a)"></div></div>`}
function render(){const page=document.getElementById('progress');if(!page)return;let box=document.getElementById('progress2');if(!box){box=document.createElement('div');box.id='progress2';page.insertBefore(box,page.firstChild)}const h=hist(),t=trend(h),r14=recent(h,14),r30=recent(h,30),rate=cleanRate(r30),ci=checkins(),safe=recent(safety(),30),p=['Flexión','Remo','Dominada'].map(progression).filter(Boolean);box.innerHTML=`<div class="eyebrow">Progreso 2.0 · interpretación automática</div><h2>${t[0]} ${t[1]}</h2><div class="alert good">${t[2]}</div><div class="stats"><div><strong>${sessions(r14)}</strong><span>sesiones · 14 días</span></div><div><strong>${weekCount(h,0)}/5</strong><span>esta semana</span></div><div><strong>${rate==null?'—':rate+'%'}</strong><span>series limpias · 30 días</span></div><div><strong>${ci.length}</strong><span>check-ins</span></div></div><h3>Tu nivel actual</h3>${p.map((x,i)=>`<div class="card"><strong>${['Flexión','Remo','Dominada'][i]}</strong><div class="mini">Nivel ${x.lvl+1}/${x.total} · ${x.name} · objetivo ${x.target} ${x.unit}</div>${bar(x.pct)}</div>`).join('')}<h3>Qué está influyendo</h3><div class="card"><strong>😴 Recuperación</strong><div class="mini">${checkinInsight()}</div></div><div class="card"><strong>🛡️ Seguridad</strong><div class="mini">${safetyInsight()}</div></div><div class="card"><strong>📈 Lectura del Coach</strong><div class="mini">${next(h,p,safe)}</div></div><p class="mini">El panel describe tus registros; no sustituye una valoración médica ni interpreta dolor como progreso deportivo.</p>`}
function next(h,p,safe){if(!h.length)return 'Empieza por completar las sesiones previstas con técnica cómoda. No necesitas pruebas máximas.';if(safe.some(x=>x.severity==='Intenso'))return 'Hay un evento reciente de dolor intenso registrado. No uses el progreso como motivo para forzar ese movimiento.';const rate=cleanRate(recent(h,30));if(rate!==null&&rate<60)return 'Ahora mismo conviene consolidar técnica y dificultad actual antes de buscar una progresión.';const two=weekCount(h,0)+weekCount(h,1);if(two<4)return 'La mejora más valiosa ahora es la constancia. Mantén el plan y deja que Coach 2.0 ajuste la dificultad.';return 'La base reciente es consistente. Sigue el objetivo que marque Coach 2.0; las progresiones se decidirán con sesiones limpias, no por una sola marca.'}
setTimeout(render,0);window.addEventListener('pageshow',()=>setTimeout(render,0));const oldGo=window.go;if(typeof oldGo==='function')window.go=function(id){const r=oldGo.apply(this,arguments);if(id==='progress')setTimeout(render,0);return r};window.CalisteniaProgress2={render,version:V};})();