/* Calistenia Trainer · Fase 9E · Sustituciones y Seguridad 2.0 */
(function(){
'use strict';
const VERSION='1.0',KEY='ct_safety_events_v1';
let ctx=null;
const SUBS={
 'Step-up':{default:'Zancada inversa asistida',where:'Junto a una barra estable',tech:'Sujétate suavemente. Paso atrás corto y controlado; rodilla alineada.',target:5,unit:'reps/pierna'},
 'Zancada inversa asistida':{default:'Sentadilla',where:'Suelo estable',tech:'Cadera atrás, rodillas alineadas y rango cómodo.',target:8,unit:'reps'},
 'Plancha':{default:'Dead bug',where:'Suelo o esterilla',tech:'Espalda cómoda contra el suelo. Extiende brazo y pierna contrarios sin arquear la zona lumbar.',target:5,unit:'reps/lado'},
 'Dead bug':{default:'Plancha inclinada',where:'Barra horizontal alta',tech:'Cuerpo alineado y abdomen activo. Cuanto más alta la barra, más fácil.',target:15,unit:'segundos'},
 'Flexión':{default:'Flexión más fácil',where:'Barra horizontal más alta',tech:'Usa una barra más alta y mantén cuerpo alineado. Sin dolor.',sameProgression:true},
 'Remo':{default:'Remo más vertical',where:'Barra horizontal estable',tech:'Acerca los pies a la barra para quedar más vertical y reducir dificultad. Sin tirones.',sameProgression:true},
 'Dominada':{default:'Colgado con apoyo parcial',where:'Barra alta con apoyo seguro de pies',tech:'Descarga parte del peso con los pies. Hombros controlados; no fuerces si hay dolor.',sameProgression:true},
 'Sentadilla':{default:'Sentadilla asistida',where:'Junto a barra estable',tech:'Sujétate ligeramente para controlar equilibrio y rango cómodo.',target:8,unit:'reps'},
 'Curl alterno':{default:'Curl martillo ligero',where:'Mancuernas',tech:'Reduce carga y mantén codos pegados. Si la molestia continúa, omite el ejercicio.',target:8,unit:'reps/brazo'},
 'Curl martillo':{default:'Curl alterno ligero',where:'Mancuernas',tech:'Reduce carga y mueve sin balanceo. Si la molestia continúa, omite el ejercicio.',target:8,unit:'reps/brazo'},
 'Curl concentración':{default:'Curl alterno ligero',where:'Mancuernas',tech:'Carga cómoda, codos controlados. Si molesta, omite el ejercicio.',target:8,unit:'reps/brazo'}
};
const REASONS=['Demasiado difícil','No entiendo el ejercicio','Barra ocupada','No tengo esa estructura','Molestia','Otro'];
const AREAS=['Hombro','Codo','Muñeca','Espalda','Cadera','Rodilla','Tobillo','Otra'];
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return []}}
function saveEvent(e){const h=load();h.unshift(e);localStorage.setItem(KEY,JSON.stringify(h.slice(0,200)))}
function inject(){if(document.getElementById('safety2Modal'))return;const st=document.createElement('style');st.textContent='.s2Modal{position:fixed;z-index:155;inset:0;background:#0009;display:none;align-items:end;justify-content:center;padding:14px}.s2Modal.show{display:flex}.s2Card{width:min(100%,620px);max-height:92vh;overflow:auto;background:var(--card);color:var(--text);border-radius:22px;padding:18px}.s2Choices{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:8px 0 14px}.s2Choices button{background:var(--card);border:1px solid var(--line);font-size:12px}.s2Choices button.sel{border-color:var(--a);outline:3px solid #1769aa22;background:var(--soft)}';document.head.appendChild(st);const m=document.createElement('div');m.id='safety2Modal';m.className='s2Modal';m.innerHTML='<div class="s2Card"><div class="eyebrow">Seguridad 2.0</div><h2 id="s2Title">Cambiar ejercicio</h2><div id="s2Body"></div><div class="grid"><button id="s2Cancel" class="secondary">CANCELAR</button><button id="s2Confirm" class="primary">CONTINUAR</button></div></div>';document.body.appendChild(m);document.getElementById('s2Cancel').onclick=close;document.getElementById('s2Confirm').onclick=confirm}
function choiceHtml(kind,vals){return '<div class="s2Choices">'+vals.map(v=>'<button data-s2="'+kind+'" data-value="'+esc(v)+'">'+esc(v)+'</button>').join('')+'</div>'}
function bindChoices(){document.querySelectorAll('[data-s2]').forEach(b=>b.onclick=()=>{const k=b.dataset.s2;document.querySelectorAll('[data-s2="'+k+'"]').forEach(x=>x.classList.remove('sel'));b.classList.add('sel')})}
function selected(k){const b=document.querySelector('[data-s2="'+k+'"].sel');return b?b.dataset.value:null}
function open(mode){inject();const ex=window.currentExercise||currentExercise;if(!ex)return;ctx={mode,base:ex.base,exercise:ex};const body=document.getElementById('s2Body');document.getElementById('s2Title').textContent=mode==='pain'?'Parar este ejercicio':'Cambiar ejercicio';if(mode==='pain'){body.innerHTML='<div class="stopBox"><strong>🛑 No continúes este movimiento con dolor.</strong><div class="mini">El registro sirve para adaptar el entrenamiento; no es un diagnóstico.</div></div><h3>¿Dónde?</h3>'+choiceHtml('area',AREAS)+'<h3>Intensidad</h3>'+choiceHtml('severity',['Leve','Moderado','Intenso'])+'<p class="mini">Si el dolor es intenso, repentino, aparece con mareo, dolor en el pecho, pérdida inesperada de fuerza o te preocupa, termina la sesión y busca valoración profesional.</p>'}else{body.innerHTML='<p class="mini">Elige el motivo. La sustitución busca conservar el patrón cuando sea razonable, sin obligarte a usar una estructura insegura.</p><h3>Motivo</h3>'+choiceHtml('reason',REASONS)}bindChoices();document.getElementById('safety2Modal').classList.add('show')}
function close(){document.getElementById('safety2Modal')?.classList.remove('show');ctx=null}
function altFor(ex,reason){const cfg=SUBS[ex.base]||{default:'Omitir ejercicio'};if(cfg.sameProgression&&reason==='Demasiado difícil'){const p=ex.prog,lvl=p?levelFor(p):0;if(p&&lvl>0){const v=progressions[p][lvl-1];return {name:v.name,where:cfg.where,tech:cfg.tech,target:v.target,unit:v.unit,progression:p,temporaryLevel:lvl-1}}}return {name:cfg.default,where:cfg.where||ex.where,tech:cfg.tech||ex.tech,target:cfg.target||Math.max(1,Number(window.currentVariant?.target||currentVariant?.target||ex.fixedTarget||1)),unit:cfg.unit||(window.currentVariant?.unit||currentVariant?.unit||ex.unit),progression:null}}
function applyAlt(reason,extra){const ex=ctx.exercise,alt=altFor(ex,reason),oldName=(window.currentVariant||currentVariant)?.name||ex.base;ex.safetyOriginal={base:ex.base,prog:ex.prog,where:ex.where,tech:ex.tech};ex.base=alt.name;ex.prog=null;ex.where=alt.where;ex.tech=alt.tech;ex.fixedTarget=alt.target;ex.unit=alt.unit;const event={id:Date.now(),date:new Date().toISOString(),session:window.sn||sn,original:oldName,base:ctx.base,replacement:alt.name,reason,...extra,version:VERSION};saveEvent(event);window.CT_SAFETY_LAST=event;close();if(typeof render==='function')render();const msg=document.getElementById('msg');if(msg)msg.innerHTML='<span class="warntxt"><strong>Sustitución temporal:</strong> '+esc(alt.name)+'. No cambia tu nivel permanente.</span>'}
function skipExercise(extra){const ex=ctx.exercise,event={id:Date.now(),date:new Date().toISOString(),session:window.sn||sn,original:(window.currentVariant||currentVariant)?.name||ex.base,base:ctx.base,replacement:'Omitido',reason:'Dolor',...extra,version:VERSION};saveEvent(event);window.CT_SAFETY_LAST=event;close();if(typeof i!=='undefined'&&typeof items!=='undefined'){if(i<items.length-1){i++;set=1;if(typeof resetExerciseClock==='function')resetExerciseClock();render();go('train')}else{const msg=document.getElementById('msg');if(msg)msg.innerHTML='<span class="stoptxt">Último ejercicio omitido por dolor. Usa SALIR si no te encuentras seguro para continuar.</span>'}}}
function confirm(){if(!ctx)return;if(ctx.mode==='pain'){const area=selected('area'),severity=selected('severity');if(!area||!severity)return;if(severity==='Intenso'){skipExercise({area,severity});return}const cfg=SUBS[ctx.base];if(cfg)applyAlt('Molestia/dolor',{area,severity});else skipExercise({area,severity});return}const reason=selected('reason');if(!reason)return;applyAlt(reason,{})}
function addButton(){const complete=document.getElementById('complete');if(!complete||document.getElementById('safetySwap'))return;const b=document.createElement('button');b.id='safetySwap';b.className='secondary full';b.style.marginTop='8px';b.textContent='🔄 CAMBIAR EJERCICIO';complete.insertAdjacentElement('afterend',b);b.onclick=()=>open('swap')}
function hookPain(){document.querySelectorAll('[data-pain="Dolor"]').forEach(b=>{const old=b.onclick;b.onclick=function(e){if(old)old.call(this,e);setTimeout(()=>open('pain'),0)}})}
function annotateFinish(){const old=window.finish;if(typeof old!=='function')return;window.finish=function(){try{const events=load().filter(e=>e.session===(window.sn||sn)&&Date.now()-e.id<6*60*60*1000);if(events.length){const ls=window.logs||logs;ls.forEach(l=>l.safetyEvents=events.map(e=>({original:e.original,replacement:e.replacement,reason:e.reason,area:e.area||null,severity:e.severity||null})))}}catch(e){console.warn('Safety2 annotation',e)}return old()}}
inject();addButton();setTimeout(()=>{addButton();hookPain();annotateFinish()},0);window.CalisteniaSafety2={open,load,version:VERSION};
})();