/* Calistenia Trainer · Fase 9G · Animaciones y biblioteca 2.0 */
(function(){'use strict';const V='1.0';
const LIB={
'Sentadilla':{cat:'Piernas',setup:'Pies aproximadamente al ancho de hombros sobre suelo firme.',move:'Lleva la cadera atrás y abajo; vuelve empujando el suelo.',cues:['Rodillas en la dirección de los pies','Pecho cómodo y estable','Rango sin dolor'],errors:['Rodillas colapsan hacia dentro','Talones pierden apoyo','Bajar más de lo controlable'],easy:'Sentadilla asistida sujetándote a una barra',hard:'Más repeticiones con la misma técnica'},
'Flexión':{cat:'Empuje',setup:'Manos sobre una barra horizontal estable. Cuanto más alta, más fácil.',move:'Cuerpo en bloque: acerca el pecho a la barra y empuja hasta volver.',cues:['Cabeza-cadera-talones alineados','Codos aproximadamente 30–45°','Abdomen activo'],errors:['Cadera cae','Hombros encogidos','Abrir demasiado los codos'],easy:'Usa una barra más alta',hard:'Usa una barra algo más baja'},
'Remo':{cat:'Tirón',setup:'Agarra una barra estable y coloca el cuerpo muy vertical al empezar.',move:'Lleva el pecho hacia la barra juntando suavemente las escápulas; baja controlado.',cues:['Cuerpo firme','Pecho hacia la barra','Sin tirones'],errors:['Tirar solo con brazos','Cadera se hunde','Encoger hombros'],easy:'Colócate más vertical',hard:'Colócate más horizontal'},
'Dominada':{cat:'Tirón',setup:'Usa la barra alta. En niveles iniciales permite apoyo parcial de pies cuando corresponda.',move:'Sigue exactamente la variante indicada por el Coach; no busques una dominada completa antes de tiempo.',cues:['Hombros controlados','Movimiento lento','Sin balanceo'],errors:['Saltar para completar repeticiones','Forzar con dolor','Balancearse'],easy:'Apoyo parcial o variante anterior',hard:'Solo cuando Coach 2.0 lo indique'},
'Step-up':{cat:'Piernas',setup:'SOLO plataforma plana, ancha y fija. Nunca una barra redonda.',move:'Apoya todo el pie, sube controlado y baja sin dejarte caer.',cues:['Pie completo apoyado','Rodilla alineada','Altura cómoda'],errors:['Usar barra redonda','Impulsarse con rebote','Plataforma inestable'],easy:'Zancada inversa asistida',hard:'Más repeticiones, no más riesgo'},
'Zancada inversa asistida':{cat:'Piernas',setup:'De pie junto a una barra estable para apoyo ligero.',move:'Da un paso atrás, baja dentro de un rango cómodo y vuelve.',cues:['Apoyo suave de la mano','Rodilla delantera estable','Paso controlado'],errors:['Perder equilibrio','Golpear la rodilla contra el suelo','Paso demasiado largo'],easy:'Menor rango',hard:'Menos ayuda de la mano'},
'Plancha':{cat:'Core',setup:'Antebrazos o manos apoyados; cuerpo largo y estable.',move:'Mantén la posición respirando, sin buscar aguantar a cualquier precio.',cues:['Abdomen activo','Glúteos suaves','Respira'],errors:['Cadera cae','Contener respiración','Dolor lumbar'],easy:'Plancha inclinada',hard:'Más segundos'},
'Dead bug':{cat:'Core',setup:'Boca arriba, caderas y rodillas flexionadas, abdomen activo.',move:'Aleja brazo y pierna contrarios sin perder control lumbar; vuelve y alterna.',cues:['Movimiento lento','Espalda cómoda','Respira'],errors:['Arquear lumbar','Mover demasiado rápido','Forzar rango'],easy:'Mueve solo piernas o brazos',hard:'Mayor extensión controlada'},
'Curl alterno':{cat:'Bíceps',setup:'De pie estable con una mancuerna en cada mano.',move:'Flexiona un codo sin balancear el tronco; baja controlado y alterna.',cues:['Codo cerca del cuerpo','Muñeca neutra','Bajada lenta'],errors:['Balancearse','Subir hombro','Dejar caer la mancuerna'],easy:'Menos peso',hard:'Más repeticiones antes que saltos grandes de peso'},
'Curl martillo':{cat:'Bíceps',setup:'Mancuernas con palmas enfrentadas.',move:'Flexiona el codo manteniendo agarre neutro y baja controlado.',cues:['Codos quietos','Tronco estable','Control'],errors:['Impulso de espalda','Codos avanzan mucho','Bajada rápida'],easy:'Menos peso',hard:'Más repeticiones controladas'},
'Curl concentración':{cat:'Bíceps',setup:'Sentado, brazo apoyado de forma estable en la cara interna del muslo.',move:'Flexiona el codo y baja despacio manteniendo el brazo estable.',cues:['Sin impulso','Rango cómodo','Bajada controlada'],errors:['Mover hombro','Rebotar abajo','Carga excesiva'],easy:'Menos peso',hard:'Excéntrica más lenta'}
};
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function key(n){if(!n)return null;for(const k of Object.keys(LIB))if(n===k||n.startsWith(k)||n.includes(k))return k;return null}
function svg(k){const common='<line x1="18" y1="132" x2="222" y2="132" stroke="currentColor" stroke-width="4" opacity=".18"/>';if(k==='Flexión')return `<svg viewBox="0 0 240 150">${common}<line x1="175" y1="25" x2="175" y2="132" stroke="currentColor" stroke-width="7"/><line x1="130" y1="58" x2="220" y2="58" stroke="currentColor" stroke-width="7"/><g class="pose p1"><circle cx="103" cy="67" r="11"/><line x1="112" y1="75" x2="154" y2="94"/><line x1="154" y1="94" x2="198" y2="119"/><line x1="122" y1="79" x2="146" y2="58"/></g><g class="pose p2"><circle cx="121" cy="54" r="11"/><line x1="130" y1="63" x2="164" y2="83"/><line x1="164" y1="83" x2="201" y2="119"/><line x1="139" y1="68" x2="172" y2="58"/></g></svg>`;if(k==='Sentadilla')return `<svg viewBox="0 0 240 150">${common}<g class="pose p1"><circle cx="105" cy="35" r="12"/><line x1="105" y1="47" x2="105" y2="90"/><line x1="105" y1="90" x2="82" y2="130"/><line x1="105" y1="90" x2="128" y2="130"/></g><g class="pose p2"><circle cx="135" cy="58" r="12"/><line x1="128" y1="68" x2="108" y2="96"/><line x1="108" y1="96" x2="78" y2="128"/><line x1="108" y1="96" x2="145" y2="128"/></g></svg>`;if(k==='Remo')return `<svg viewBox="0 0 240 150">${common}<line x1="175" y1="28" x2="175" y2="132" stroke="currentColor" stroke-width="7"/><line x1="105" y1="60" x2="218" y2="60" stroke="currentColor" stroke-width="7"/><g class="pose p1"><circle cx="75" cy="66" r="11"/><line x1="84" y1="74" x2="125" y2="103"/><line x1="125" y1="103" x2="151" y2="130"/><line x1="92" y1="78" x2="125" y2="60"/></g><g class="pose p2"><circle cx="112" cy="61" r="11"/><line x1="121" y1="69" x2="143" y2="96"/><line x1="143" y1="96" x2="157" y2="130"/><line x1="128" y1="73" x2="165" y2="60"/></g></svg>`;if(k==='Dominada')return `<svg viewBox="0 0 240 150"><line x1="45" y1="25" x2="195" y2="25" stroke="currentColor" stroke-width="8"/><g class="pose p1"><circle cx="120" cy="73" r="12"/><line x1="120" y1="85" x2="120" y2="122"/><line x1="120" y1="88" x2="88" y2="27"/><line x1="120" y1="88" x2="152" y2="27"/></g><g class="pose p2"><circle cx="120" cy="49" r="12"/><line x1="120" y1="61" x2="120" y2="105"/><line x1="120" y1="65" x2="91" y2="27"/><line x1="120" y1="65" x2="149" y2="27"/></g></svg>`;return `<svg viewBox="0 0 240 150">${common}<g class="pose p1"><circle cx="92" cy="42" r="12"/><line x1="92" y1="54" x2="92" y2="98"/><line x1="92" y1="98" x2="72" y2="130"/><line x1="92" y1="98" x2="112" y2="130"/></g><g class="pose p2"><circle cx="142" cy="42" r="12"/><line x1="142" y1="54" x2="142" y2="98"/><line x1="142" y1="98" x2="122" y2="130"/><line x1="142" y1="98" x2="162" y2="130"/></g></svg>`}
function injectStyle(){if(document.getElementById('v2style'))return;const s=document.createElement('style');s.id='v2style';s.textContent='.v2visual{background:linear-gradient(180deg,var(--soft),transparent);border:1px solid var(--line);border-radius:18px;padding:10px;margin:10px 0}.v2visual svg{width:100%;height:180px;stroke:currentColor;stroke-width:6;stroke-linecap:round;stroke-linejoin:round;fill:none}.v2visual circle{fill:currentColor;stroke:none}.v2visual .pose{animation:v2pose 2.4s ease-in-out infinite}.v2visual .p2{animation-delay:-1.2s}@keyframes v2pose{0%,42%{opacity:1}50%,92%{opacity:.12}100%{opacity:1}}.v2cue{display:grid;grid-template-columns:1fr 1fr;gap:8px}.v2box{border:1px solid var(--line);border-radius:13px;padding:10px}.v2box ul{margin:5px 0 0;padding-left:18px}.v2legend{font-size:12px;font-weight:800;letter-spacing:.05em}.v2libcard{cursor:pointer}';document.head.appendChild(s)}
function visualFor(name){const k=key(name),d=LIB[k];if(!d)return '';return `<div class="v2visual"><div class="eyebrow">Guía visual · ${esc(d.cat)}</div>${svg(k)}<div class="v2legend">↔ Alterna entre posición inicial y final</div></div><div class="v2cue"><div class="v2box"><strong>✅ CLAVES</strong><ul>${d.cues.map(x=>'<li>'+esc(x)+'</li>').join('')}</ul></div><div class="v2box"><strong>⚠️ EVITA</strong><ul>${d.errors.map(x=>'<li>'+esc(x)+'</li>').join('')}</ul></div></div><div class="v2box" style="margin-top:8px"><strong>1 · COLÓCATE</strong><div class="mini">${esc(d.setup)}</div><strong>2 · MUÉVETE</strong><div class="mini">${esc(d.move)}</div><div class="mini" style="margin-top:6px">Más fácil: ${esc(d.easy)} · Siguiente paso: ${esc(d.hard)}</div></div>`}
function enhanceTrain(){const ex=window.currentExercise||window.currentVariant||null;const name=(window.currentExercise&&window.currentExercise.base)||(window.currentVariant&&window.currentVariant.name);if(!name)return;let host=document.getElementById('v2TrainGuide');if(!host){const complete=document.getElementById('complete'),anchor=complete&&complete.parentElement;if(!anchor)return;host=document.createElement('div');host.id='v2TrainGuide';anchor.insertBefore(host,complete)}host.innerHTML=visualFor(name)}
function addLibrary(){const page=document.getElementById('library')||document.getElementById('exercises');if(!page||document.getElementById('v2Library'))return;const box=document.createElement('div');box.id='v2Library';box.innerHTML='<div class="eyebrow">Biblioteca 2.0</div><h2>Aprende antes de entrenar</h2><p class="mini">Toca un ejercicio para ver colocación, movimiento, claves y errores.</p>'+Object.entries(LIB).map(([k,d])=>`<details class="card v2libcard"><summary><strong>${esc(k)}</strong> · <span class="mini">${esc(d.cat)}</span></summary>${visualFor(k)}</details>`).join('');page.appendChild(box)}
injectStyle();setTimeout(()=>{addLibrary();enhanceTrain()},0);const oldRender=window.render;if(typeof oldRender==='function')window.render=function(){const r=oldRender.apply(this,arguments);setTimeout(enhanceTrain,0);return r};window.CalisteniaVisuals2={library:LIB,visualFor,version:V};})();